// Copyright (c) Rapid Software LLC. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Scada.Admin.Actions;
using Scada.Comm.Devices;
using Scada.Log;

namespace Scada.Comm.Drivers.DrvHttpNotif.View
{
    /// <summary>
    /// Provides web administrator actions for the HTTP notification driver.
    /// <para>Предоставляет действия веб-администратора для драйвера HTTP-уведомлений.</para>
    /// </summary>
    public sealed class AdminActionProvider
    {
        /// <summary>
        /// Returns channel prototypes generated by the WinForms device view.
        /// </summary>
        [AdminAction(AdminActionIds.GetTags)]
        public Task<AdminActionResult> GetTags(
            AdminActionContext context, CancellationToken cancellationToken)
        {
            try
            {
                cancellationToken.ThrowIfCancellationRequested();

                List<HttpNotifTagRow> rows = CnlPrototypeFactory.GetGroup().CnlPrototypes
                    .Select(ToRow)
                    .ToList();

                return Task.FromResult(AdminActionResult.Table(new
                {
                    columns = new[] { "name", "tagCode", "cnlTypeID", "formatCode" },
                    rows
                }));
            }
            catch (Exception ex)
            {
                return Task.FromResult(AdminActionResult.Error(
                    ex.BuildErrorMessage("HTTP notification tag generation failed")));
            }
        }

        private static HttpNotifTagRow ToRow(CnlPrototype prototype)
        {
            return new HttpNotifTagRow
            {
                Name = prototype.Name,
                TagCode = prototype.TagCode,
                CnlTypeID = prototype.CnlTypeID,
                FormatCode = prototype.FormatCode
            };
        }

        private sealed class HttpNotifTagRow
        {
            public string Name { get; set; } = "";
            public string TagCode { get; set; } = "";
            public int CnlTypeID { get; set; }
            public string FormatCode { get; set; } = "";
        }
    }
}
