// Copyright (c) Rapid Software LLC. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Scada.Admin.Actions;
using Scada.Log;

namespace Scada.Comm.Drivers.DrvCsvReader.View
{
    /// <summary>
    /// Provides web administrator actions for the CSV reader driver.
    /// <para>Предоставляет действия веб-администратора для драйвера чтения CSV.</para>
    /// </summary>
    public sealed class AdminActionProvider
    {
        /// <summary>
        /// Returns channel prototypes generated by tag count.
        /// </summary>
        [AdminAction(AdminActionIds.GetTags)]
        [AdminActionArgs(typeof(GetTagsArgs))]
        public Task<AdminActionResult> GetTags(
            AdminActionContext context, CancellationToken cancellationToken)
        {
            try
            {
                cancellationToken.ThrowIfCancellationRequested();

                GetTagsArgs args = context.GetArgs<GetTagsArgs>();
                int tagCount = Math.Max(0, args.TagCount);
                List<CsvTagRow> rows = [];

                for (int tagNum = 1; tagNum <= tagCount; tagNum++)
                {
                    cancellationToken.ThrowIfCancellationRequested();

                    string tagCode = "Tag" + tagNum;
                    rows.Add(new CsvTagRow
                    {
                        Name = tagCode,
                        TagCode = tagCode
                    });
                }

                return Task.FromResult(AdminActionResult.Table(new
                {
                    columns = new[] { "name", "tagCode" },
                    rows
                }));
            }
            catch (Exception ex)
            {
                return Task.FromResult(AdminActionResult.Error(
                    ex.BuildErrorMessage("CSV reader tag generation failed")));
            }
        }

        private sealed class GetTagsArgs
        {
            public int TagCount { get; set; } = 1;
        }

        private sealed class CsvTagRow
        {
            public string Name { get; set; } = "";
            public string TagCode { get; set; } = "";
        }
    }
}
