// Copyright (c) Rapid Software LLC. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Scada.Admin.Actions;
using Scada.Data.Const;
using Scada.Log;

namespace Scada.Comm.Drivers.DrvEmail.View
{
    /// <summary>
    /// Provides web administrator actions for the Email driver.
    /// <para>Предоставляет действия веб-администратора для драйвера Email.</para>
    /// </summary>
    public sealed class AdminActionProvider
    {
        /// <summary>
        /// Returns channel prototypes generated by the WinForms device view.
        /// </summary>
        [AdminAction(AdminActionIds.GetTags)]
        public Task<AdminActionResult> GetTags(
            AdminActionContext context, CancellationToken cancellationToken)
        {
            try
            {
                cancellationToken.ThrowIfCancellationRequested();

                EmailTagRow[] rows =
                [
                    new()
                    {
                        Name = TagName.Mail,
                        TagCode = TagCode.Mail,
                        CnlTypeID = CnlTypeID.InputOutput,
                        FormatCode = FormatCode.N0
                    },
                    new()
                    {
                        Name = TagName.MailAttach,
                        TagCode = TagCode.MailAttach,
                        CnlTypeID = CnlTypeID.InputOutput,
                        FormatCode = FormatCode.N0
                    }
                ];

                return Task.FromResult(AdminActionResult.Table(new
                {
                    columns = new[] { "name", "tagCode", "cnlTypeID", "formatCode" },
                    rows
                }));
            }
            catch (Exception ex)
            {
                return Task.FromResult(AdminActionResult.Error(
                    ex.BuildErrorMessage("Email tag generation failed")));
            }
        }

        private sealed class EmailTagRow
        {
            public string Name { get; set; } = "";
            public string TagCode { get; set; } = "";
            public int CnlTypeID { get; set; }
            public string FormatCode { get; set; } = "";
        }
    }
}
