<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <FileVersion>6.5.0.0</FileVersion>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Scada.Comm.Drivers.DrvOpcUa</RootNamespace>
    <Authors>Mikhail Shiryaev</Authors>
    <Company>Rapid Software LLC</Company>
    <Product>Rapid SCADA</Product>
    <Copyright>Copyright © 2026</Copyright>
    <Version>6.5.0.0</Version>
    <AssemblyVersion>6.5.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Config\DrvOpcUa.Linux.xml" />
    <None Remove="Config\DrvOpcUa.Win.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Config\DrvOpcUa.Linux.xml" />
    <EmbeddedResource Include="Config\DrvOpcUa.Win.xml" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Configuration" Version="1.5.374.54" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="1.5.374.54" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ScadaCommCommon">
      <HintPath>..\..\..\System\ScadaComm\ScadaCommCommon\bin\$(Configuration)\net10.0\ScadaCommCommon.dll</HintPath>
    </Reference>
    <Reference Include="ScadaCommon">
      <HintPath>..\..\..\System\ScadaCommon\ScadaCommon\bin\$(Configuration)\net10.0\ScadaCommon.dll</HintPath>
    </Reference>
    <Reference Include="ScadaCommon.Log">
      <HintPath>..\..\..\System\ScadaCommon\ScadaCommon.Log\bin\$(Configuration)\net10.0\ScadaCommon.Log.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>



