// Copyright (c) Rapid Software LLC. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Scada.Admin.Actions;
using Scada.Comm.Devices;
using Scada.Log;

namespace Scada.Comm.Drivers.DrvSimulator.View
{
    /// <summary>
    /// Provides web administrator actions for the device simulator driver.
    /// <para>Предоставляет действия веб-администратора для драйвера симулятора устройства.</para>
    /// </summary>
    public sealed class AdminActionProvider
    {
        /// <summary>
        /// Returns channel prototypes generated by the WinForms device view.
        /// </summary>
        [AdminAction(AdminActionIds.GetTags)]
        public Task<AdminActionResult> GetTags(
            AdminActionContext context, CancellationToken cancellationToken)
        {
            try
            {
                cancellationToken.ThrowIfCancellationRequested();

                List<SimulatorTagRow> rows = [];

                foreach (CnlPrototypeGroup group in CnlPrototypeFactory.GetGroups())
                {
                    cancellationToken.ThrowIfCancellationRequested();

                    rows.AddRange(group.CnlPrototypes.Select(prototype => ToRow(group.Name, prototype)));
                }

                return Task.FromResult(AdminActionResult.Table(new
                {
                    columns = new[] { "group", "name", "tagCode", "cnlTypeID", "formatCode", "quantityCode", "unitCode", "dataLen" },
                    rows
                }));
            }
            catch (Exception ex)
            {
                return Task.FromResult(AdminActionResult.Error(
                    ex.BuildErrorMessage("Simulator tag generation failed")));
            }
        }

        private static SimulatorTagRow ToRow(string groupName, CnlPrototype prototype)
        {
            return new SimulatorTagRow
            {
                Group = groupName,
                Name = prototype.Name,
                TagCode = prototype.TagCode,
                CnlTypeID = prototype.CnlTypeID,
                FormatCode = prototype.FormatCode,
                QuantityCode = prototype.QuantityCode,
                UnitCode = prototype.UnitCode,
                DataLen = prototype.DataLen
            };
        }

        private sealed class SimulatorTagRow
        {
            public string Group { get; set; } = "";
            public string Name { get; set; } = "";
            public string TagCode { get; set; } = "";
            public int CnlTypeID { get; set; }
            public string FormatCode { get; set; } = "";
            public string QuantityCode { get; set; } = "";
            public string UnitCode { get; set; } = "";
            public int? DataLen { get; set; }
        }
    }
}
